### ISSUE TITLE
minting failed because of Error: Candy Guard Bot Tax triggered. Check transaction && public: redeemedAmount Too many NFTs redeemed!

### ISSUE THREAD

**Issue by loadev** [MarkSackerberg/umi-cmv3-ui-inofficial#11]
![image](https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/117549351/38cc06ab-a346-4b63-a604-14ddee152483)
minting failed because of Error: Candy Guard Bot Tax triggered. Check transaction
and
public: redeemedAmount Too many NFTs redeemed!

my groups and guards:

```
"groups": [
    {
      "label": "WL",
        "guards": {
            "botTax": {
            "value": 0.02,
            "lastInstruction": true
          },
            "tokenPayment": {
            "amount": 100000,
            "mint": "FPe8nxvZADrfaDLDPBXXXXXXXXXXR6CjXnRwt8Q67Vc",
            "destinationAta": "2GVFJyhxxxxxxxxEyo8hndW5ijE2JYMr"
          },
          "startDate": {
            "date": "2024-01-01T09:00:00Z"
          },
          "mintLimit": {
            "id": 1,
            "limit": 1
          },
          "allowList": {
            "merkleRoot": "e30059cd0c9eba5a8xxxxxxxx25287493e7057c195a401e23a0236624126a8"
          }
        }
      },
      {
        "label": "public",
         "guards": {
            "botTax": {
            "value": 0.02,
            "lastInstruction": true
          },
            "tokenPayment": {
            "amount": 100000,
            "mint": "FPe8nxvZADrfaDLDPBXXXXXXXXnRwt8Q67Vc",
            "destinationAta": "2GVFJyhiR82AwXXXXXXXXXXhndW5ijE2JYMr"
          },
          "startDate": {
            "date": "2024-01-01T09:00:00Z"
          },
          "redeemedAmount": {
            "maximum": 2
          },
          "mintLimit": {
            "id": 2,
            "limit": 1
          }
        }
      }
  ]
}
}
```

**Comment by loadev** [comment]
if i remove "botTax" from the guard it still gives me error.
![image](https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/117549351/c15e7b57-2b60-49c6-8259-b83811352a0e)
![image](https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/117549351/620a2a22-54a1-4161-9e00-16bda3f8390b)

**Comment by loadev** [comment]
```
export const mintText = [
  { label: "WL", mintText: "WL mint paying with $BOLLY", buttonLabel: "Mint now!", header: "WL Mint" },
  { label: "public", mintText: "Mint Paying with $BOLLY", buttonLabel: "Mint now!", header: "Public Mint" },
];
```
i got two mint phases, one with Whitelist and another one public, both have limitation of 1 mint per wallet, but the public should me limited to 80 NFTS max.

```
"redeemedAmount": {
            "maximum": 2
          },
```
the button is greyed out and the console says the following:
![image](https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/117549351/f6191616-e9df-4a8c-a1b5-f4ed042d3594)
![image](https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/117549351/d06cd0e8-04f7-413c-a415-a7c7aec1bd98)

**Comment by loadev** [comment]
Firstly, I would like to express my gratitude for making this repository available, as we know there is no official UI for Candy Machine V3 yet, and if this one works, it will be more than sufficient. I also thank you in advance for any help you can provide regarding the two issues I mentioned.

**Comment by MarkSackerberg** [comment]
Hey @loadev
let me cite the [docs](https://developers.metaplex.com/candy-machine/guards/redeemed-amount):
> The Redeemed Amount guard forbids minting when the number of minted NFTs for the entire Candy Machine reaches the configured maximum amount.

If you set the redeemedAmount to 2 for the public group this group can not mint anymore after two NFTs (in the whole candy machine) are minted.

You probably want to completely remove the redeemedAmount guard completely and change the mintLimit to 80 instead.

This issue is not related to the UI, but candy machine itself though. Therefore I am closing the issue now, feel free to head to the [metaplex discord](https://discord.gg/metaplex) to ask your questions :)

**Comment by loadev** [comment]
Thanks for the help.
The issue was from my side, first i was not using the correct "destinationAta", and secondly for the "public" mint i was not using the proper argument to limit the sales
```
 "allocation" : {
            "id": 1,
            "limit": 8
          }, 
```

So the correct config file is:

```
{
  "tokenStandard": "nft",
  "number": 10,
  "symbol": "NB",
  "sellerFeeBasisPoints": 500,
  "isMutable": true,
  "isSequential": false,
  "creators": [
    {
      "address": "2ChiR8CCCCCCCCCCCCCCCCCCCCCCCCCCCCE2JYMr",
      "share": 100
    }
  ],
  "uploadMethod": "bundlr",
  "ruleSet": null,
  "awsConfig": null,
  "sdriveApiKey": null,
  "nftStorageAuthToken": null,
  "shdwStorageAccount": null,
  "pinataConfig": null,
  "hiddenSettings": null,
  "maxEditionSupply": null,
  "guards": {
    "default": {
  },
  "groups": [
    {
      "label": "WL",
        "guards": {
            "botTax": {
            "value": 0.02,
            "lastInstruction": true
          },
            "tokenPayment": {
            "amount": 100000000000,
            "mint": "FPe8nxvZADCCCCCCCCCCCCCCCCCCCCCCCCCXnRwt8Q67Vc",
            "destinationAta": "D5qiTCCCCCCCCCCCCCCCCCCCCCCCCUzHhjnNN"
          },
          "startDate": {
            "date": "2024-01-01T09:00:00Z"
          },
          "mintLimit": {
            "id": 1,
            "limit": 1
          },
          "allowList": {
            "merkleRoot": "c58b3CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCc2bc1daba2165a"
          }
        }
      },
      {
        "label": "public",
         "guards": {
            "botTax": {
            "value": 0.02,
            "lastInstruction": true
          },
            "tokenPayment": {
            "amount": 100000000000,
            "mint": "FPe8nxvZADrCCCCCCCCCCCCCCCCRwt8Q67Vc",
            "destinationAta": "D5qiT4CCCCCCCCCCCCCCCCCCCUzHhjnNN"
          },
          "startDate": {
            "date": "2024-01-01T09:00:00Z"
          },
          "allocation" : {
            "id": 1,
            "limit": 8
          }, 
          "mintLimit": {
            "id": 2,
            "limit": 1
          }
        }
      }
  ]
}
}
```

DO NOT FORGET TO LOGIN INTO THE "ADMIN DASH" TO ACTIVATE THE GUARDS AND OBTAIN THE PUBLIC_LUT.


THANK YOU AGAIN IT REALLY HELPED :)
