### ISSUE TITLE
fulfilled and rejected transactions are not clear

### ISSUE THREAD

**Issue by moefreelancer83** [MarkSackerberg/umi-cmv3-ui-inofficial#14]
Hi there, 
in `components/mintButton.tsx`
I was wondering if the fulfilledCount and rejectedCount are referring to Promise status or to the return of the sendPromises function.

`https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/blob/a3661c4cb873a5e50662b7cb3fc34ac665b3afd3/components/mintButton.tsx#L204`

For example I see that my first tx is rejected, but the Promise.allSettled result for first tx is fulfilled.

**Comment by MarkSackerberg** [comment]
Hi, they are just for the promises, the results of the transactions are not checked.
This might be a good thing to add.

**Comment by MarkSackerberg** [comment]
closed this too early. I've clarified this for the user.
