### ISSUE TITLE
"No Candy guard found!" error

### ISSUE THREAD

**Issue by Flaming19** [MarkSackerberg/umi-cmv3-ui-inofficial#28]
Candy Machine Id : 6RwRXFa1ZZjaKYMxa4AWMCP8NTiXk5rpE2LMnTSj8USJ
Config File:
{
    "number": 2,
    "symbol": "PTIN",
    "sellerFeeBasisPoints": 500,
    "isMutable": true,
    "isSequential": false,
    "ruleSet": null,
    "creators": [
        {
            "address": "C265AseyuAfcsG3KZsddsMemWZFJ9QEK1gj1v1itaVJR",
            "share": 100
        }
    ],    
    "uploadMethod": "bundlr",
    "awsS3Bucket": null,
    "retainAuthority": true,
    "awsConfig": null,
    "nftStorageAuthToken": null,
    "shdwStorageAccount": null,
    "pinataConfig": null,
    "hiddenSettings": null,
    "guards": {
        "default": {
          "solPayment": {
            "value": 0.01,
            "destination": "BwWoCNYYVFWg7aSmCQTVgjyfDakUWejSJ3LUVHE7ng79"
          },
          "startDate": {
            "date": "2024-05-23T20:00:00Z"
          }
        }
      }    
}

Could you please help me out in this. I tried everything but not able to resolve this error. 
Thankyou

<img width="521" alt="Screenshot 2024-06-12 at 6 31 44 PM" src="https://github.com/MarkSackerberg/umi-cmv3-ui-inofficial/assets/83865068/6603cc18-a4a6-4765-9da1-f566e3cbc35b">

**Comment by MarkSackerberg** [comment]
You did not attach a guard, just defined them in the config.
Run 
`sugar guard add`
To resolve this
