### ISSUE TITLE
The CM from .env is invalid

### ISSUE THREAD

**Issue by Flaming19** [MarkSackerberg/umi-cmv3-ui-inofficial#29]
Access to fetch at 'https://api.devnet.solana.com/' from origin 'https://vCam.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.Understand this error
api.devnet.solana.com/:1 **(error in fetch candymachine details)**

* where we can add 'Access-Control-Allow-Origin: *'

**Comment by Flaming19** [comment]
Reminder! please help.

**Comment by MarkSackerberg** [comment]
Since you opened a different issue where you said devnet is working fine i assume this has been resolved? What was your issue?

**Comment by Flaming19** [comment]
No, This is different issue.
This issue is related to CORs [This occurs when we redirect a website eg. Domain on godaddy and code deployed on amazon]

**Comment by Flaming19** [comment]
Some more issues are also there like if i try to build a project[npm run build ] then we always get 

Route (pages)                              Size     First Load JS
┌ ○ / (549 ms)                             51.7 kB         478 kB
├   └ css/31bd8d1e36aa4795.css             655 B
├   /_app                                  0 B             426 kB
└ ○ /404                                   182 B           426 kB
+ First Load JS shared by all              428 kB
  ├ chunks/framework-ce01d25dbf7cad32.js   45.2 kB
  ├ chunks/main-69a178ab7f70753f.js        26.9 kB
  ├ chunks/pages/_app-de5193defbc53d42.js  352 kB
  ├ chunks/webpack-61d55cae69bdfcbf.js     1.85 kB
  └ css/ffe08882759a85d4.css               1.82 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

**Comment by MarkSackerberg** [comment]
The CORS issue is not related to the code here. 

The second thing you mention I don’t see any error message?

**Comment by Flaming19** [comment]
Please find attachment 
<img width="781" alt="Screenshot 2024-08-01 at 4 12 45 PM" src="https://github.com/user-attachments/assets/7f613374-e6ed-42ae-817b-471fb47da41e">

**Comment by MarkSackerberg** [comment]
This is still not a error message. The UI will work just fine.

**Comment by Flaming19** [comment]
> This is still not a error message. The UI will work just fine.

Thankyou
