### ISSUE TITLE
403 Forbidden error | mainnet-beta [https://api.mainnet-beta.solana.com]

### ISSUE THREAD

**Issue by Flaming19** [MarkSackerberg/umi-cmv3-ui-inofficial#30]
Error: 403 :  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "faa3a5cf-dd21-40c3-8a76-540c7e44f3b9" } 

Working fine on devnet url.

Thank-you in advance

**Comment by MarkSackerberg** [comment]
Do not use the public RPC.
There are free options from extrnode, quicknode, helius if you need it for testing.
