### ISSUE TITLE
malicious transaction error

### ISSUE THREAD

**Issue by Flaming19** [MarkSackerberg/umi-cmv3-ui-inofficial#31]
<img width="357" alt="Screenshot 2024-08-09 at 1 38 15 PM" src="https://github.com/user-attachments/assets/66e4f8d1-b29c-4afd-9978-28c7d33c2725">

How can we resolve this error.
This error occurs when we trying to mint a NFT on Mainnet.

Thanks

**Comment by MarkSackerberg** [comment]
You need to do what the error message tells you: contact that email address.
It is not related to the UI but automatically applies to all new domains.
Other wallets, which are not using blowfish, are working perfectly fine.
